### PR TITLE
Add "flip image" option and functionality

### PR DESCRIPTION
**Pull request by Hely0n**
As I stated in the Issue, I implemented the possibility to flip the image horizontally, as there are many camera mounts that are upside down.

### CODE REVIEW

**Comment by mryel00** [comment]
Hey, thank you for the commit 😄 
Maybe you could add a vertical flip too as this might be wanted by someone in the future.
There could then maybe be a third option `upsidedown`  or something like this that applies both at once.
So in the end we would have `flip_horizontal`, `flip_vertical` and `upsidedown`.

**Comment by Hely0n** [comment]
Never mind! Thank you, that I hadn't to return my new Pi Camera 3 😄 .

I thought about adding other rotations too, but wanted to wait for actual demand from a user.

**Comment by mryel00** [comment]
I didn't meant other rotations like 90° or 270°.
Atm you have implemented `upsidedown` (180° rotation). Now it would be nice if you could:
1. Change the name of `flip` to something like `upsidedown`
2. Add only a horizontal and only a vertical flip option
If you don't want to do it, just response again and I will do it myself.

**Comment by Hely0n** [comment]
Okay so you mean "flip" in the sense of "mirror"? Because the point of my implementation was to make camera mounts usable, where the cable comes from the top(like mine). So the two other rotations would make sense for appropriate camera mounts. But why would anyone mirror the image vertically?

**Comment by Hely0n** [comment]
But mirroring would be very easy to implement, As I would just to omit the "flip_h" parameter I think. Will try that later today.

**Comment by mryel00** [comment]
Yes I mean flip in the sense of mirror. The flip term is used like this in the official documentation of picamera2.
This project is mainly targeting 3D printing but if you for example want to use it for a streaming setup and want to mirror it directly through spyglass then this could be helpful.
Just an edge case most of the times but there are always people who want to use it, so we can implement it directly with a feature similar to this.
`libcamera.Transform(hflip=1, vflip=1)` just passing one of them with 1 would make the correct flip. So shouldn't be that hard.
I appreciate your effort a lot 😄

**Comment by Hely0n** [comment]
Okay I understand what you mean! I will do this now.

And yeah you are right, the word "flip" wasn't my best pick from a developer perspective 😆

**Comment by Hely0n** [comment]
I commited it and tried to rotate the image too with the "rotation" parameter, but it doesn't seem to work as intended. 
rotation=90 without vflip and hflip makes it upsidedown.

**Review by mryel00 — APPROVED** [review]
You were close to what I thought. I changed the upsidedown as a 180° rotation option so that you have the correct orientation of the picture after you mirror it horizontally. It just applies the vertical mirror option too.
So now you can mirror it vertically, mirror it horizontally and rotate it by 180°. The third option is redundant as it is the first to options applied both at once but makes it easier for new users.

**Pull request merged**
